services:
  db:
    image: postgres:15
    container_name: rental_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=quanlythuenha
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: rental_web
    command: python website/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=quanlythuenha
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_HOST=db  # Quan trọng: Trong Docker, host chính là tên service 'db'
      - DB_PORT=5432
      - MAILTRAP_API_TOKEN=2dbec931bbd8d55fcd69d4f053c4a3fe
    depends_on:
      - db

volumes:
  postgres_data: