# Generated by Django 6.0.1 on 2026-01-30 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nội thất')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả tình trạng')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên căn nhà/Tòa nhà')),
                ('address', models.TextField(verbose_name='Địa chỉ nhà')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ (Latitude)')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Kinh độ (Longitude)')),
                ('total_rooms', models.PositiveIntegerField(default=0, verbose_name='Tổng số phòng')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='Tên phòng / Số phòng')),
                ('area', models.IntegerField(default=20, verbose_name='Diện tích (m2)')),
                ('price', models.IntegerField(verbose_name='Giá cho thuê (VNĐ)')),
                ('deposit', models.IntegerField(verbose_name='Tiền cọc (VNĐ)')),
                ('max_people', models.IntegerField(default=4, verbose_name='Số người ở tối đa')),
                ('current_people', models.IntegerField(default=0, verbose_name='Số người đang ở')),
                ('is_rented', models.BooleanField(default=False, verbose_name='Trạng thái thuê?')),
                ('furnitures', models.ManyToManyField(blank=True, to='quanly.furniture', verbose_name='Nội thất đi kèm')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.house', verbose_name='Thuộc căn nhà')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100, verbose_name='Họ tên khách thuê')),
                ('tenant_phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('tenant_id', models.CharField(max_length=20, verbose_name='CCCD/CMND')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu thuê')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc thuê')),
                ('total_value', models.IntegerField(blank=True, null=True, verbose_name='Tổng giá trị hợp đồng (VNĐ)')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.room', verbose_name='Phòng thuê')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/', verbose_name='Hình ảnh phòng')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quanly.room')),
            ],
        ),
    ]
