# Generated by Django 6.0.1 on 2026-02-05 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nội thất')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả tình trạng')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_phone', models.CharField(max_length=10, verbose_name='Số điện thoại')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Căn Nhà')),
                ('house_type', models.CharField(choices=[('nguyencan', 'Nhà nguyên căn'), ('chungcu', 'Căn hộ chung cư'), ('phong_tro', 'Phòng Trọ')], default='phong_tro', max_length=20, verbose_name='Loại nhà')),
                ('price', models.IntegerField(verbose_name='Giá cho thuê (VNĐ)')),
                ('deposit', models.IntegerField(verbose_name='Tiền cọc (VNĐ)')),
                ('area', models.IntegerField(default=20, verbose_name='Diện tích nhà (m2)')),
                ('district', models.CharField(choices=[('q1', 'Quận 1'), ('q2', 'Quận 2'), ('q3', 'Quận 3'), ('q4', 'Quận 4'), ('q5', 'Quận 5'), ('q6', 'Quận 6'), ('q7', 'Quận 7'), ('q8', 'Quận 8'), ('q9', 'Quận 9'), ('q10', 'Quận 10'), ('qtb', 'Quận Tân Bình'), ('qtp', 'Quận Tân Phú'), ('qbt', 'Quận Bình Thạnh'), ('td', 'Thủ Đức')], max_length=10, verbose_name='Chọn Quận')),
                ('address', models.TextField(verbose_name='Địa chỉ nhà')),
                ('lat', models.FloatField(default=0.0, verbose_name='Vĩ độ')),
                ('long', models.FloatField(default=0.0, verbose_name='Kinh độ')),
                ('max_people', models.IntegerField(default=4, verbose_name='Số người ở tối đa')),
                ('current_people', models.IntegerField(default=0, verbose_name='Số người đang ở')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả căn nhà')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='house/', verbose_name='Ảnh đại diện phòng')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('hidden', 'Đã ẩn'), ('rejected', 'Bị từ chối')], max_length=20, verbose_name='Trạng thái')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Chủ nhà')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100, verbose_name='Họ tên khách thuê')),
                ('tenant_phone', models.CharField(max_length=10, verbose_name='Số điện thoại')),
                ('tenant_id', models.CharField(max_length=20, verbose_name='CCCD')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu thuê')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc thuê')),
                ('total_value', models.IntegerField(blank=True, null=True, verbose_name='Tổng giá trị hợp đồng (VNĐ)')),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quanly.house', verbose_name='Hợp đồng thuê cho nhà')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/', verbose_name='Hình ảnh')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quanly.house')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='Số phòng')),
                ('area', models.IntegerField(default=20, verbose_name='Diện tích phòng (m2)')),
                ('furnitures', models.ManyToManyField(blank=True, to='quanly.furniture', verbose_name='Nội thất đi kèm')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.house', verbose_name='Thuộc căn nhà')),
            ],
        ),
    ]
