# Generated by Django 6.0.1 on 2026-01-30 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='total_rooms',
        ),
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Trạng thái duyệt bài cho thuê?'),
        ),
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Chủ nhà/Người cho thuê'),
        ),
        migrations.AlterField(
            model_name='house',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='lon',
            field=models.FloatField(default=0.0, verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên Căn Nhà / Tòa nhà'),
        ),
    ]
