# Generated by Django 6.0.2 on 2026-02-22 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='current_people',
        ),
        migrations.RemoveField(
            model_name='house',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='house',
            name='long',
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hiệu lực'), ('expired', 'Đã hết hạn'), ('terminated', 'Đã chấm dứt sớm')], default='active', max_length=20, verbose_name='Trạng thái hợp đồng'),
        ),
        migrations.AddField(
            model_name='house',
            name='furnitures',
            field=models.ManyToManyField(blank=True, to='quanly.furniture', verbose_name='Nội thất đi kèm'),
        ),
        migrations.AddField(
            model_name='house',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tọa độ vị trí (Point)'),
        ),
        migrations.AddField(
            model_name='house',
            name='room_count',
            field=models.IntegerField(default=1, verbose_name='Số lượng phòng ngủ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(verbose_name='Ngày kết thúc hợp đồng'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='quanly.house', verbose_name='Hợp đồng cho'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='Ngày bắt đầu hiệu lực'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenant_phone',
            field=models.CharField(max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_value',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tổng giá trị hợp đồng (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ chi tiết (Số nhà, Ngõ/Hẻm, Đường)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.FloatField(default=0.0, verbose_name='Diện tích sàn (m2)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='deposit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tiền cọc (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='house',
            name='district',
            field=models.CharField(choices=[('q1', 'Quận 1'), ('q2', 'Quận 2'), ('q3', 'Quận 3'), ('q4', 'Quận 4'), ('q5', 'Quận 5'), ('q6', 'Quận 6'), ('q7', 'Quận 7'), ('q8', 'Quận 8'), ('q9', 'Quận 9'), ('q10', 'Quận 10'), ('q11', 'Quận 11'), ('q12', 'Quận 12'), ('qbt', 'Quận Bình Thạnh'), ('qtb', 'Quận Tân Bình'), ('qtp', 'Quận Tân Phú'), ('qp', 'Quận Phú Nhuận'), ('qgv', 'Quận Gò Vấp'), ('qbtan', 'Quận Bình Tân'), ('td', 'Thành phố Thủ Đức'), ('hbc', 'Huyện Bình Chánh'), ('hhm', 'Huyện Hóc Môn'), ('hcc', 'Huyện Củ Chi'), ('hnb', 'Huyện Nhà Bè'), ('hcg', 'Huyện Cần Giờ')], max_length=10, verbose_name='Khu vực Quận/Huyện'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('nguyencan', 'Nhà nguyên căn / Nhà phố'), ('chungcu', 'Căn hộ chung cư'), ('bietthu', 'Biệt thự')], default='nguyencan', max_length=20, verbose_name='Loại Hình Nhà'),
        ),
        migrations.AlterField(
            model_name='house',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='house/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề bài đăng / Tên căn nhà'),
        ),
        migrations.AlterField(
            model_name='house',
            name='owner_phone',
            field=models.CharField(max_length=15, verbose_name='Số điện thoại liên hệ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.BigIntegerField(verbose_name='Giá cho thuê (VNĐ/Tháng)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('available', 'Đang cho thuê'), ('rented', 'Đã cho thuê'), ('hidden', 'Đã ẩn'), ('rejected', 'Bị từ chối')], default='pending', max_length=20, verbose_name='Trạng thái cho thuê'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(upload_to='house_images/', verbose_name='Hình ảnh thêm'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
