# Generated by Django 6.0.1 on 2026-02-22 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_rename_create_at_house_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='unit_count',
            field=models.IntegerField(default=1, verbose_name='Số lượng căn'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='quanly.house', verbose_name='Nhà/Căn hộ cho thuê'),
        ),
        migrations.AlterField(
            model_name='house',
            name='room_count',
            field=models.IntegerField(default=1, verbose_name='Số lượng phòng'),
        ),
    ]
