# Generated by Django 6.0.1 on 2026-02-24 03:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0003_house_unit_count_alter_contract_house_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='furnitures',
            new_name='furniture',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tenant_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tenant_phone',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='description',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Bản scan Hợp đồng/CCCD (PDF/ZIP)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối'),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_price',
            field=models.CharField(blank=True, default='Theo giá nhà nước', max_length=100, verbose_name='Giá điện'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_negotiable',
            field=models.BooleanField(default=False, verbose_name='Giá thỏa thuận'),
        ),
        migrations.AddField(
            model_name='house',
            name='water_price',
            field=models.CharField(blank=True, default='Theo giá nhà nước', max_length=100, verbose_name='Giá nước'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='quanly.house', verbose_name='Nhà/Căn hộ cho thuê'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_value',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng giá trị hợp đồng (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Diện tích sàn (m2)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='deposit',
            field=models.BigIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiền cọc (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Chủ nhà'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá cho thuê (VNĐ/Tháng)'),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên khách thuê')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('cccd', models.CharField(max_length=20, verbose_name='CCCD')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Nơi thường trú')),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='tenants/id_cards/', verbose_name='Ảnh CCCD mặt trước')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='tenants/id_cards/', verbose_name='Ảnh CCCD mặt sau')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Quản lý bởi Chủ nhà')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='signed_contracts', to='quanly.tenant', verbose_name='Người đại diện ký hợp đồng'),
        ),
        migrations.AddField(
            model_name='contract',
            name='roommates',
            field=models.ManyToManyField(blank=True, related_name='shared_contracts', to='quanly.tenant', verbose_name='Thành viên ở ghép'),
        ),
    ]
