# Generated by Django 6.0.1 on 2026-02-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0004_rename_furnitures_house_furniture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='location',
        ),
        migrations.AddField(
            model_name='house',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ (Latitude)'),
        ),
        migrations.AddField(
            model_name='house',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ (Longitude)'),
        ),
    ]
