# Generated by Django 6.0.2 on 2026-03-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('available', 'Còn trống'), ('rented', 'Đã cho thuê'), ('hidden', 'Đã ẩn'), ('rejected', 'Bị từ chối')], default='pending', max_length=20, verbose_name='Trạng thái cho thuê'),
        ),
    ]
