# Generated by Django 6.0.1 on 2026-04-04 11:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nội thất')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_phone', models.CharField(max_length=15, verbose_name='Số điện thoại liên hệ')),
                ('name', models.CharField(max_length=200, verbose_name='Tiêu đề bài đăng / Tên căn nhà')),
                ('house_type', models.CharField(choices=[('nguyencan', 'Nhà nguyên căn / Nhà phố'), ('chungcu', 'Căn hộ chung cư'), ('bietthu', 'Biệt thự')], default='nguyencan', max_length=20, verbose_name='Loại Hình Nhà')),
                ('price', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá cho thuê (VNĐ/Tháng)')),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='Giá thỏa thuận')),
                ('deposit', models.BigIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiền cọc (VNĐ)')),
                ('electricity_price', models.CharField(blank=True, default='Theo giá nhà nước', max_length=100, verbose_name='Giá điện')),
                ('water_price', models.CharField(blank=True, default='Theo giá nhà nước', max_length=100, verbose_name='Giá nước')),
                ('area', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Diện tích sàn (m2)')),
                ('unit_count', models.IntegerField(default=1, verbose_name='Số lượng căn')),
                ('room_count', models.IntegerField(default=1, verbose_name='Số lượng phòng')),
                ('max_people', models.IntegerField(default=4, verbose_name='Số người ở tối đa')),
                ('district', models.CharField(choices=[('q1', 'Quận 1'), ('q2', 'Quận 2'), ('q3', 'Quận 3'), ('q4', 'Quận 4'), ('q5', 'Quận 5'), ('q6', 'Quận 6'), ('q7', 'Quận 7'), ('q8', 'Quận 8'), ('q9', 'Quận 9'), ('q10', 'Quận 10'), ('q11', 'Quận 11'), ('q12', 'Quận 12'), ('qbt', 'Quận Bình Thạnh'), ('qtb', 'Quận Tân Bình'), ('qtp', 'Quận Tân Phú'), ('qp', 'Quận Phú Nhuận'), ('qgv', 'Quận Gò Vấp'), ('qbtan', 'Quận Bình Tân'), ('td', 'Thành phố Thủ Đức'), ('hbc', 'Huyện Bình Chánh'), ('hhm', 'Huyện Hóc Môn'), ('hcc', 'Huyện Củ Chi'), ('hnb', 'Huyện Nhà Bè'), ('hcg', 'Huyện Cần Giờ')], max_length=10, verbose_name='Khu vực Quận/Huyện')),
                ('address', models.TextField(verbose_name='Địa chỉ chi tiết (Số nhà, Ngõ/Hẻm, Đường)')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ (Latitude)')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Kinh độ (Longitude)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='house/', verbose_name='Ảnh đại diện')),
                ('status', models.CharField(choices=[('no_coordinates', 'Chưa có tọa độ'), ('pending', 'Chờ duyệt'), ('available', 'Còn trống'), ('rented', 'Đã cho thuê'), ('hidden', 'Đã ẩn'), ('rejected', 'Bị từ chối')], default='pending', max_length=20, verbose_name='Trạng thái cho thuê')),
                ('requires_coordinates', models.BooleanField(default=False, verbose_name='Cần nhập tọa độ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('furniture', models.ManyToManyField(blank=True, to='houses.furniture', verbose_name='Nội thất đi kèm')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Chủ nhà')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/', verbose_name='Hình ảnh thêm')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houses.house')),
            ],
        ),
    ]
