# Generated by Django 6.0.1 on 2026-04-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_housefurnitureitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='district',
            field=models.CharField(blank=True, choices=[('q1', 'Quận 1'), ('q2', 'Quận 2'), ('q3', 'Quận 3'), ('q4', 'Quận 4'), ('q5', 'Quận 5'), ('q6', 'Quận 6'), ('q7', 'Quận 7'), ('q8', 'Quận 8'), ('q9', 'Quận 9'), ('q10', 'Quận 10'), ('q11', 'Quận 11'), ('q12', 'Quận 12'), ('qbt', 'Quận Bình Thạnh'), ('qtb', 'Quận Tân Bình'), ('qtp', 'Quận Tân Phú'), ('qp', 'Quận Phú Nhuận'), ('qgv', 'Quận Gò Vấp'), ('qbtan', 'Quận Bình Tân'), ('td', 'Thành phố Thủ Đức'), ('hbc', 'Huyện Bình Chánh'), ('hhm', 'Huyện Hóc Môn'), ('hcc', 'Huyện Củ Chi'), ('hnb', 'Huyện Nhà Bè'), ('hcg', 'Huyện Cần Giờ')], max_length=10, null=True, verbose_name='Khu vực Quận/Huyện'),
        ),
    ]
