# Generated by Django 6.0.2 on 2026-04-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_housefurnitureitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='district',
        ),
    ]
