# Generated by Django 6.0.2 on 2026-05-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_housefurnitureitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('about', 'Về chúng tôi'), ('service_ky_gui', 'Dịch vụ ký gửi nhà cho thuê'), ('terms', 'Điều khoản sử dụng')], unique=True, verbose_name='Mã trang')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề trang')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Trang tĩnh',
                'verbose_name_plural': 'Trang tĩnh',
            },
        ),
    ]
