# Generated by Django 6.0.1 on 2026-04-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_house_district'),
        ('houses', '0003_remove_house_district'),
    ]

    operations = [
    ]
