# Generated by Django 6.0.1 on 2026-04-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_merge_20260419_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='district',
        ),
    ]
