# Generated by Django 6.0.1 on 2026-04-04 11:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên khách thuê')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('cccd', models.CharField(max_length=20, verbose_name='CCCD')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Nơi thường trú')),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='tenants/id_cards/', verbose_name='Ảnh CCCD mặt trước')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='tenants/id_cards/', verbose_name='Ảnh CCCD mặt sau')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Quản lý bởi Chủ nhà')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu hiệu lực')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc hợp đồng')),
                ('total_value', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng giá trị hợp đồng (VNĐ)')),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Bản scan Hợp đồng/CCCD (PDF/ZIP)')),
                ('status', models.CharField(choices=[('active', 'Đang hiệu lực'), ('expired', 'Đã hết hạn'), ('terminated', 'Đã chấm dứt sớm')], default='active', max_length=20, verbose_name='Trạng thái hợp đồng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='houses.house', verbose_name='Nhà/Căn hộ cho thuê')),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='signed_contracts', to='contracts.tenant', verbose_name='Người đại diện ký hợp đồng')),
                ('roommates', models.ManyToManyField(blank=True, related_name='shared_contracts', to='contracts.tenant', verbose_name='Thành viên ở ghép')),
            ],
        ),
    ]
