# Generated by Django 6.0.1 on 2026-04-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='cccd',
            field=models.CharField(max_length=20, unique=True, verbose_name='CCCD'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại'),
        ),
    ]
